try 2

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -61,21 +61,21 @@ jobs:
             /p:CollectCoverage=true /p:CoverletOutput=TestResults/coverage-results/ /p:CoverletOutputFormat=cobertura
         continue-on-error: true
 
-      # Discord notification on success
-      - name: Send Discord Notification on Success
-        if: success()
-        run: |
-          curl -X POST -H "Content-Type: application/json" \
-          -d '{"content":"✅ Tests passed for version ${{ matrix.version }}!", "embeds": [{"image": {"url": "https://media.giphy.com/media/3a53VvGpzUgh05qq7W/giphy.gif"}}]}' \
-          ${{ secrets.DISCORD_SECRET_WEBHOOK }}
+      # # Discord notification on success
+      # - name: Send Discord Notification on Success
+      #   if: success()
+      #   run: |
+      #     curl -X POST -H "Content-Type: application/json" \
+      #     -d '{"content":"✅ Tests passed for version ${{ matrix.version }}!", "embeds": [{"image": {"url": "https://media.giphy.com/media/3a53VvGpzUgh05qq7W/giphy.gif"}}]}' \
+      #     ${{ secrets.DISCORD_SECRET_WEBHOOK }}
 
-      # Discord notification on failure
-      - name: Send Discord Notification on Failure
-        if: failure()
-        run: |
-          curl -X POST -H "Content-Type: application/json" \
-          -d '{"content":"❌ Tests failed for version ${{ matrix.version }}. Please check the logs.", "embeds": [{"image": {"url": "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzByYm1qcnZlOTJlMWM3YXdkZXJ0NWR2MnEzd3I2aXFia2FvMzBhNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/D7knpKzFbgDPBmdrVM/giphy.gif"}}]}' \
-          ${{ secrets.DISCORD_SECRET_WEBHOOK }}
+      # # Discord notification on failure
+      # - name: Send Discord Notification on Failure
+      #   if: failure()
+      #   run: |
+      #     curl -X POST -H "Content-Type: application/json" \
+      #     -d '{"content":"❌ Tests failed for version ${{ matrix.version }}. Please check the logs.", "embeds": [{"image": {"url": "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzByYm1qcnZlOTJlMWM3YXdkZXJ0NWR2MnEzd3I2aXFia2FvMzBhNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/D7knpKzFbgDPBmdrVM/giphy.gif"}}]}' \
+      #     ${{ secrets.DISCORD_SECRET_WEBHOOK }}
 
       - name: Install ReportGenerator
         if: matrix.language == 'csharp'
@@ -163,6 +163,28 @@ jobs:
           else
             echo "### No coverage data found." >> $GITHUB_STEP_SUMMARY
           fi
+
+          if (( $(echo "$total_percentage >= 80" | bc -l) )); then
+            echo "Coverage is above 80% threshold."
+          else
+            echo "Coverage is below 80% threshold."
+            exit 1
+          fi
+
+          - send a notification to Discord
+          - name: Send Discord Notification on Success
+            if: success()
+            run: |
+              curl -X POST -H "Content-Type: application/json" \
+              -d '{"content":"✅ Tests passed for version ${{ matrix.version }}!", "embeds": [{"image": {"url": "https://media.giphy.com/media/3a53VvGpzUgh05qq7W/giphy.gif"}}]}' \
+              ${{ secrets.DISCORD_SECRET_WEBHOOK }}
+          
+          - name: Send Discord Notification on Failure
+            if: failure()
+            run: |
+              curl -X POST -H "Content-Type: application/json" \
+              -d '{"content":"❌ Tests failed for version ${{ matrix.version }}. Please check the logs.", "embeds": [{"image": {"url": "https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzByYm1qcnZlOTJlMWM3YXdkZXJ0NWR2MnEzd3I2aXFia2FvMzBhNSZlcD12MV9naWZzX3NlYXJjaCZjdD1n/D7knpKzFbgDPBmdrVM/giphy.gif"}}]}' \
+              ${{ secrets.DISCORD_SECRET_WEBHOOK }}
 
 
   python-tests:
