Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -89,10 +89,35 @@ jobs:
     runs-on: ubuntu-latest
     needs: csharp-build-and-test  # Depends on the C# job
     steps:
-    # Checkout the code
+     # Checkout the code
     - name: Checkout code
       uses: actions/checkout@v4
-  
+
+    # Setup for .NET (C#)
+    - name: Setup .NET
+      uses: actions/setup-dotnet@v3
+      with:
+        dotnet-version: '8.0.x'
+
+    # Run C# application
+    - name: Start C# Application
+      run: |
+        nohup dotnet run --project ./V1/Cargohub/Werehouses.csproj --urls=http://localhost:3000 &
+
+    # Wait for the C# application to be ready
+    - name: Wait for C# Application
+      run: |
+        echo "Waiting for C# application to start..."
+        for i in {1..30}; do
+          if curl --silent --fail http://localhost:3000; then
+            echo "C# application is running."
+            exit 0
+          fi
+          sleep 2
+        done
+        echo "C# application failed to start."
+        exit 1
+
     # Setup for Python
     - name: Set up Python
       uses: actions/setup-python@v5
@@ -106,7 +131,7 @@ jobs:
     # Run Python Tests and Generate Report
     - name: Run Python Tests
       run: |
-        mkdir -p PythonTests/reports
+        mkdir -p ./PythonTests/reports
         python -m xmlrunner discover -o ./PythonTests/reports
 
     # Upload Python Test Reports
@@ -115,4 +140,3 @@ jobs:
       with:
         name: python-test-reports
         path: ./PythonTests/reports
-
