sixth test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -88,7 +88,12 @@ jobs:
     - name: Enforce coverage threshold
       if: matrix.language == 'csharp'
       run: |
-        coverage=$(cat TestResults/coverage-report-${{ matrix.version }}/coverage.cobertura.xml| grep -oP 'd+(?=%)')
+        coverage=$(cat TestResults/**/coverage.cobertura.xml| grep -oP 'd+(?=%)')
+        if [ ! -s TestResults/coverage-summary.txt ]; then
+          echo "Coverage file is missing or empty"
+          exit 1
+        fi
+
         if [$coverage -lt 80]; then
         echo "Coverage is less than 80% ($coverage%)"
         exit 1
